# Generated by Django 5.2.1 on 2025-06-03 15:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='qwertyuiop')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 6, 3, 15, 36, 47, 292194, tzinfo=datetime.timezone.utc), verbose_name='срок действия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
