# Generated by Django 5.2.1 on 2025-06-03 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'ordering': ('created_at',), 'verbose_name': 'код активации', 'verbose_name_plural': 'коды активации'},
        ),
        migrations.RemoveField(
            model_name='codes',
            name='created_date',
        ),
        migrations.AddField(
            model_name='codes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(default='qwertyuiop', verbose_name='код активации'),
        ),
    ]
