# Generated by Django 5.2.1 on 2025-08-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
    ]
