# Generated by Django 5.2.1 on 2025-08-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_initial'),
        ('users', '0003_remove_client_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='images.image', verbose_name='аватар пользователя'),
        ),
    ]
