# Generated by Django 5.2.1 on 2025-08-18 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0006_initial'),
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='текст комментария')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='comments.comments', verbose_name='родительский комментарий')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post', verbose_name='статья')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(help_text='True — лайк, False — дизлайк', verbose_name='лайк?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_gallery_image', to='images.image')),
                ('public_avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_public_avatar', to='images.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто оценил')),
                ('user_avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_user_avatar', to='images.image')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('user_avatar__isnull', False), ('public_avatar__isnull', False), ('gallery_image__isnull', False), _connector='OR'), name='at_least_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('user_avatar__isnull', False), ('public_avatar__isnull', False)), models.Q(('user_avatar__isnull', False), ('gallery_image__isnull', False)), models.Q(('public_avatar__isnull', False), ('gallery_image__isnull', False)), _connector='OR', _negated=True), name='only_one_target'), models.UniqueConstraint(fields=('user', 'user_avatar'), name='unique_user_avatar_like'), models.UniqueConstraint(fields=('user', 'public_avatar'), name='unique_public_avatar_like'), models.UniqueConstraint(fields=('user', 'gallery_image'), name='unique_gallery_image_like')],
            },
        ),
    ]
