# Generated by Django 5.2.1 on 2025-06-19 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('is_private', models.BooleanField(default=False, verbose_name='приватный паблик')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('members', models.ManyToManyField(related_name='public_members', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец паблика')),
            ],
            options={
                'verbose_name': 'паблик',
                'verbose_name_plural': 'паблики',
                'ordering': ('id',),
            },
        ),
    ]
