# Generated by Django 5.2.1 on 2025-06-19 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата приглашения')),
                ('accepted', models.BooleanField(default=False, verbose_name='принято')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='кем приглашен')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invited', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_invite', to='publics.public', verbose_name='паблик')),
            ],
            options={
                'verbose_name': 'приглашение в паблик',
                'verbose_name_plural': 'приглашения в паблики',
                'ordering': ('created_at',),
            },
        ),
    ]
