# Generated by Django 5.2.1 on 2025-07-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_gallery_images_remove_gallery_public_and_more'),
        ('publics', '0002_publicinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicinvite',
            name='public',
        ),
        migrations.RemoveField(
            model_name='publicinvite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='publicinvite',
            name='invited_user',
        ),
        migrations.DeleteModel(
            name='Public',
        ),
        migrations.DeleteModel(
            name='PublicInvite',
        ),
    ]
