# Generated by Django 5.2.1 on 2025-07-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_images_user_images_created_at_avatar_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='public',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
